/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M21
 * Generated at: 2017-09-14 07:52:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.blog.settings;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class categories_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/국기%204월(오후)%20박보라/MyType/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/workProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1502088492389L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".box {\r\n");
      out.write("\tborder: 1px solid;\r\n");
      out.write("\tborder-color: #d9d9d9;\r\n");
      out.write("\tmargin: 20px;\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("\tcolor: #a6a6a6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("\tbackground-color: #4CAF50; /* Green */\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 8px 20px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tmargin: 4px 2px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button1 {\r\n");
      out.write("\tbackground-color: #303030;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button2 {\r\n");
      out.write("\tbackground-color: #cccccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cate-bt {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-xs-0 col-md-2\"></div>\r\n");
      out.write("<div class=\"col-xs-12 col-md-8\">\r\n");
      out.write("\t<div class=\"form-group box\">\r\n");
      out.write("\t\t<h3 align=\"left\" style=\"color: #262626\">카테고리 편집</h3>\r\n");
      out.write("\t\t<div align=\"right\">\r\n");
      out.write("\t\t\t<button class=\"button button2\" id=\"add\">추가</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<input class=\"form-control\" type=\"text\" value=\"전체 보기\"\r\n");
      out.write("\t\t\t\treadonly=\"readonly\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\" id=\"catelist\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6 form-group\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6 form-group\" align=\"right\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"button button1\" id=\"bt\">변경 내용\r\n");
      out.write("\t\t\t\t\t저장</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-xs-0 col-md-2\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar cate_delete = \"\";\r\n");
      out.write("\r\n");
      out.write("\t$(\".cate_up\").on(\"click\", function() {\r\n");
      out.write("\t\t$(this).parent().parent().after($(this).parent().parent().prev());\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".cate_down\").on(\"click\", function() {\r\n");
      out.write("\t\t$(this).parent().parent().before($(this).parent().parent().next());\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".cate_delete\").on(\"click\", function() {\t\r\n");
      out.write("\t\tcate_delete += $(this).parent().prev().prev().prev().children('[type=\"hidden\"]').val()+ \",\";\r\n");
      out.write("\t\t$(this).parent().parent().remove();\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#add\").on(\"click\", function() {\r\n");
      out.write("\t\t\t\t\t\tvar add = \"<div class=\\\"category-row row\\\"><div class=\\\"col-xs-9 col-md-9 form-group\\\">\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"<input class=\\\"form-control cate_name\\\" type=\\\"text\\\" name=\\\"addcate_name\\\"/>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"<input type=\\\"hidden\\\" name=\\\"addcate_id\\\" class=\\\"cate_id\\\" />\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</div><div class=\\\"col-xs-1 col-md-1 form-group\\\">\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"<button class=\\\"form-control cate-bt cate_up\\\"><i class=\\\"glyphicon glyphicon-chevron-up\\\"></i></button>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</div><div class=\\\"col-xs-1 col-md-1 form-group\\\"><button class=\\\"form-control cate-bt cate_down\\\"><i class=\\\"glyphicon glyphicon-chevron-down\\\"></i></button>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</div><div class=\\\"col-xs-1 col-md-1 form-group\\\"><button class=\\\"form-control cate-bt cate_delete\\\"><i class=\\\"glyphicon glyphicon-remove\\\"></i></button></div></div>\";\r\n");
      out.write("\t\t\t\t\t\t$(\"#catelist\").append(add);\r\n");
      out.write("\t\t\t\t\t\t$(\".cate_up\").attr('onclick', '').unbind('click');\r\n");
      out.write("\t\t\t\t\t\t$(\".cate_delete\").attr('onclick', '').unbind('click');\r\n");
      out.write("\t\t\t\t\t\t$(\".cate_delete\").on(\"click\", function() {\r\n");
      out.write("\t\t\t\t\t\t\tcate_delete += $(this).parent().prev().prev().prev().children('[type=\"hidden\"]').val() + \",\";\r\n");
      out.write("\t\t\t\t\t\t\t$(this).parent().parent().remove();\t\t\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\".cate_up\").on(\"click\", function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(this).parent().parent().after($(this).parent().parent().prev());\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\".cate_down\").on(\"click\", function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(this).parent().parent().before($(this).parent().parent().next());\t\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#bt\").on(\"click\", function() {\r\n");
      out.write("\t\tvar cate_name_order = \"\";\r\n");
      out.write("\t\tvar addcate_name = \"\";\r\n");
      out.write("\t\tvar a1 = $('[name=addcate_name]');\r\n");
      out.write("\t\tvar a2 = $('[name=cate_name]');\r\n");
      out.write("\t\tfor (var i = 0; i < a1.length; i++) {\r\n");
      out.write("\t\t\taddcate_name += a1.eq(i).val() + \",\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\".cate_name\").each(function() {\r\n");
      out.write("\t\t\tcate_name_order += $(this).val() + \",\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$.post({\r\n");
      out.write("\t\t\t\turl : \"/blog/categoryUpdate.mt\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"cate_delete\" : cate_delete,\r\n");
      out.write("\t\t\t\t\t\"title\" : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("\t\t\t\t\t\"url\" : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("\t\t\t\t\t\"cate_name_order\" : cate_name_order,\r\n");
      out.write("\t\t\t\t\t\"addcate_name\" : addcate_name\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}).done(function(result) {\r\n");
      out.write("\t\t\t\tif(result.result){\r\n");
      out.write("\t\t\t\t\tlocation.href=\"/blog/\"+result.url+\"/categories\";\r\n");
      out.write("\t\t\t\t\twindow.alert(\"카테고리가 수정되었습니다.\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tlocation.href=\"/blog/\"+result.url+\"/categories\";\r\n");
      out.write("\t\t\t\t\twindow.alert(\"카테고리 이름은 중복하여 사용할 수 없습니다.\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/view/blog/settings/categories.jsp(59,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("obj");
      // /WEB-INF/view/blog/settings/categories.jsp(59,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/blog/settings/categories.jsp(59,3) '${list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/view/blog/settings/categories.jsp(60,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${obj.CATEGORY_NAME ne \"전체 보기\"}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class=\"category-row row\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-xs-9 col-md-9 form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<input class=\"form-control cate_name\" type=\"text\"\r\n");
          out.write("\t\t\t\t\t\t\t\tname=\"cate_name\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${obj.CATEGORY_NAME }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" /> <input\r\n");
          out.write("\t\t\t\t\t\t\t\ttype=\"hidden\" name=\"cate_id\" class=\"cate_id\"\r\n");
          out.write("\t\t\t\t\t\t\t\tvalue=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${obj.CATE_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-xs-1 col-md-1 form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<button class=\"form-control cate-bt cate_up\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-chevron-up\"></i>\r\n");
          out.write("\t\t\t\t\t\t\t</button>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-xs-1 col-md-1 form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<button class=\"form-control cate-bt cate_down\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-chevron-down\"></i>\r\n");
          out.write("\t\t\t\t\t\t\t</button>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"col-xs-1 col-md-1 form-group\">\r\n");
          out.write("\t\t\t\t\t\t\t<button class=\"form-control cate-bt cate_delete\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<i class=\"glyphicon glyphicon-remove\"></i>\r\n");
          out.write("\t\t\t\t\t\t\t</button>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
