/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M21
 * Generated at: 2017-09-12 12:25:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.blog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class postWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/국기%204월(오후)%20박보라/MyType/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/workProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1502088492389L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.5.1/css/froala_editor.pkgd.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link \r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.5.1/css/froala_style.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"\r\n");
      out.write("\tintegrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/blogViewcss.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("div#editor {\r\n");
      out.write("\twidth: 81%;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title-wrap {\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    border-bottom: 1px solid rgba(0,0,0,.09);\r\n");
      out.write("}\r\n");
      out.write("@media (min-width: 576px)\r\n");
      out.write(" .post {\r\n");
      out.write("    padding: 2.5em 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post .container {\r\n");
      out.write("    padding: 0 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".post .container {\r\n");
      out.write("    padding: 0 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("@media (min-width: 576px)\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("    width: 540px;\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("    margin-left: auto;\r\n");
      out.write("    margin-right: auto;\r\n");
      out.write("    padding-left: 15px;\r\n");
      out.write("    padding-right: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title-wrap input {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin: 10px;\r\n");
      out.write("    border-radius: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea.autosize {\r\n");
      out.write("    resize: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" .post {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    padding: 1.5em 0;\r\n");
      out.write("    margin: 20px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    overflow-x: hidden;\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.dropdown-toggle{\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a{\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (min-width: 576px){\r\n");
      out.write(".col-sm-3 {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 25%;\r\n");
      out.write("}}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("input[type=checkbox] {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=checkbox]+label {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tpadding-left: 25px;\r\n");
      out.write("\tmargin-right: 15px;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=checkbox]+label:before {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tbottom: 1px;\r\n");
      out.write("\tbackground-color: #ccc;\r\n");
      out.write("\tborder-radius: 2px;\r\n");
      out.write("\tbox-shadow: inset 0px 1px 1px 0px rgba(0, 0, 0, .3), 0px 1px 0px 0px\r\n");
      out.write("\t\trgba(255, 255, 255, .8);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=checkbox]:checked+label:before {\r\n");
      out.write("\tcontent: \"\\2714\"; /* 체크모양 */\r\n");
      out.write("\ttext-shadow: 1px 1px 1px rgba(0, 0, 0, .2);\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tfont-weight: 800;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground: #1a1a1a;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=radio] {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=radio]+label {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tpadding-left: 25px;\r\n");
      out.write("\tmargin-right: 15px;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=radio]+label:before {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\tbottom: 1px;\r\n");
      out.write("\tbackground-color: #ccc;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\tbox-shadow: inset 0px 1px 1px 0px rgba(0, 0, 0, .3), 0px 1px 0px 0px\r\n");
      out.write("\t\trgba(255, 255, 255, .8);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=radio]:checked+label:before {\r\n");
      out.write("\tcontent: \"\\2714\"; /* 체크모양 */\r\n");
      out.write("\ttext-shadow: 1px 1px 1px rgba(0, 0, 0, .2);\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tfont-weight: 800;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground: #1a1a1a;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-default {\r\n");
      out.write("\ttext-shadow: 0 1px 0 #fff;\r\n");
      out.write("\tbackground-image: -webkit-linear-gradient(top, #fff 0, #e0e0e0 100%);\r\n");
      out.write("\tbackground-image: -o-linear-gradient(top, #fff 0, #e0e0e0 100%);\r\n");
      out.write("\tbackground-image: -webkit-gradient(linear, left top, left bottom, from(#fff),\r\n");
      out.write("\t\tto(#e0e0e0));\r\n");
      out.write("\tbackground-image: linear-gradient(to bottom, #fff 0, #ffffff 100%);\r\n");
      out.write("\tfilter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffffff',\r\n");
      out.write("\t\tendColorstr='#ffffffff', GradientType=0);\r\n");
      out.write("\tfilter: progid:DXImageTransform.Microsoft.gradient(enabled=false);\r\n");
      out.write("\tbackground-repeat: repeat-x;\r\n");
      out.write("\tborder-color: #dbdbdb;\r\n");
      out.write("\tborder-color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".tagtext {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 0 0 0 32px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    line-height: 24px;\r\n");
      out.write("    border: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title::-webkit-input-placeholder {\r\n");
      out.write("   font-weight: bold; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".payment-line{\r\n");
      out.write("\tbackground-color: gray;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header>\t\t\r\n");
      out.write("\t\t<div class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-toggle\" style=\"float: left; border: 0px;\"> <span\r\n");
      out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-menu-left\"></span></a>  \r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#postNav\"> \r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> \r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"postNav\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"back\" style=\"margin-left: 200px;\"><a href=\"/blog/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.url }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\" margin-right: 0px;\"><i class=\"material-icons\">keyboard_backspace</i></a>\r\n");
      out.write("\t\t\t\t\t<li class=\"home\" style=\"margin-right: 15px;\"><a href=\"/\" style=\" margin: 0px; padding-left:0px; background-image: none; background-color: white;\"><span><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"/images/mytype.png\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li style=\"margin-right: 200px; margin-top: 15px;\"><a class=\"bnt dropdown-toggle\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\tdata-target=\"#modalPublish\"><span>발행</span></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"modal fade\" id=\"modalPublish\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\" style=\"border-bottom: 0px;\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t<h4>발행</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-3\">       \r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"form-control-label\" style=\"color: #4d4d4d;\">썸네일</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-12 col-sm-9\" style=\"margin-left: -9px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn btn-default\" href=\"#\" role=\"button\" id=\"\">썸네일 \r\n");
      out.write("\t\t\t\t\t\t\t\t선택</a> <a class=\"btn btn-default\" href=\"#\" role=\"button\" id=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-left: -10px;\">삭제</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-3\" style=\"color: #4d4d4d;\">카테고리</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-3\">  \r\n");
      out.write("\t\t\t\t\t\t<select id=\"category\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>카테고리 선택</option>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-3\" style=\"color: #4d4d4d;\">최소 후원금액</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" name=\" support\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\" support\" required style=\"width: 100px;\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-3\" style=\"margin-left: -690px; margin-top: 7px;\"> \r\n");
      out.write("\t\t\t\t\t\t<span>포인트</span> \r\n");
      out.write("\t\t\t\t\t</div>  \r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-3\" style=\"color: #4d4d4d;\">표시설정</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-9\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" id=\"notice\" class=\"checkbox-style\" /><label\r\n");
      out.write("\t\t\t\t\t\t\tfor=\"notice\">공지</label> <input type=\"checkbox\" id=\"adult\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"checkbox-style\" /><label for=\"adult\">성인물</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\" style=\"margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-3\" style=\"color: #4d4d4d;\">공개설정</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-9\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"all\" class=\"radio-style\" name=\"open\" /><label\r\n");
      out.write("\t\t\t\t\t\t\tfor=\"all\">전체 공개</label> <input type=\"radio\" id=\"my\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"radio-style\" name=\"open\" /><label for=\"my\">나만 보기</label> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"radio\" id=\"secret\" class=\"radio-style\" name=\"open\" /><label\r\n");
      out.write("\t\t\t\t\t\t\tfor=\"secret\">비밀글</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\" style=\"margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-3\" style=\"color: #4d4d4d;\">댓글 쓰기 권한</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-9\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"login\" class=\"radio-style\" name=\"comment\" /><label\r\n");
      out.write("\t\t\t\t\t\t\tfor=\"login\">로그인 사용자</label> <input type=\"radio\" id=\"buy\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"radio-style\" name=\"comment\" /><label for=\"buy\">구매자/후원자</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t          \t</div>\t         \r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\t        <div class=\"modal-footer\">\r\n");
      out.write("\t\t          <button type=\"button\" class=\"button button1\" id=\"publisher\">발행하기</button>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t    \t</div>  \t\t  \t\t\r\n");
      out.write("  \t\t</div>\r\n");
      out.write(" \t\r\n");
      out.write("  \t\r\n");
      out.write("  \t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div align=\"center\" class=\"row \">\r\n");
      out.write("\t\t\t<div class=\"col-xs-0 col-md-1\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-12 col-md-10\">\r\n");
      out.write("\t\t\t\t<article class=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin-top: 70px; margin-left: 112px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"title\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"title\" placeholder=\"제목을 입력하세요.\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 32px;\">\r\n");
      out.write("\t\t\t\t\t\t\t</div> \t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin-left: 112px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"subtitle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"subtitle\" placeholder=\"부제목을 입력하세요.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"font-size: 16px;\"> \r\n");
      out.write("\t\t\t\t\t\t\t</div>  \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"editor\" id=\"editor\">\r\n");
      out.write("\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"payment-line\" id=\"payline\" align=\"center\" contenteditable=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"material-icons\">attach_money</i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"payment-line-description\" style=\"vertical-align: top;\">— 이 선 아래쪽에 유료 콘텐츠를 작성하세요.</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tag-wrap\" style=\"margin-top: 20px;\"> \r\n");
      out.write("\t\t\t\t\t\t<label class=\"material-icons\" title=\"태그\" style=\"float: left; margin-left: 120px;\">bookmark</label>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"post-tags\" class=\"sr-only\">태그</label>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"hash\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"hash\" placeholder=\"여러 개의 태그는 공백(space)으로 구분하여 입력하세요.\" \r\n");
      out.write("\t\t\t\t\t\t\t \tclass=\"tagtext\" style=\"width: 850px; margin-left: -300px; height: 25px;\">    \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("    \r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t</article>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t<div class=\"col-xs-0 col-md-1\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/mode/xml/xml.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.5.1//js/froala_editor.pkgd.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Initialize the editor. -->\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#editor\").froalaEditor(\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\ttoolbarButtons : [ 'fontFamily', '|', 'fontSize', '|',\r\n");
      out.write("\t\t\t\t\t\t\t\t'paragraphFormat', '|', 'bold', 'italic',\r\n");
      out.write("\t\t\t\t\t\t\t\t'underline', 'undo', 'redo', 'codeView' ],\r\n");
      out.write("\t\t\t\t\tfontFamilySelection : true,\r\n");
      out.write("\t\t\t\t\tfontSizeSelection : true,\r\n");
      out.write("\t\t\t\t\tparagraphFormatSelection : true,\r\n");
      out.write("\t\t\t\t\theightMin : 100\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t$(\"[href='https://www.froala.com/wysiwyg-editor?k=u']\").eq(0).remove();\r\n");
      out.write("\t\t}, 5);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#publisher\").on(\"click\", function() {\r\n");
      out.write("\t\t\tvar prev = \"\";\r\n");
      out.write("\t\t\tvar next = \"\";\r\n");
      out.write("\t\t\t$(\"#payline\").prevAll().each(function(){\r\n");
      out.write("\t\t\t\tprev = \"<p>\" + $(this).html() +\"</p>\"+prev;\r\n");
      out.write("\t\t\t})\t\t\t\r\n");
      out.write("\t\t\t$(\"#payline\").nextAll().addClass(\"ccontent\");\r\n");
      out.write("\t\t\t$(\"#payline\").nextAll().each(function(){\r\n");
      out.write("\t\t\t\tnext += \"<p>\" + $(this).html() +\"</p>\";\r\n");
      out.write("\t\t\t})\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"/postWriter.mt\",\r\n");
      out.write("\t\t\t\tdata : {\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\"category\" : $(\"#category\").val(),\r\n");
      out.write("\t\t\t\t\t\"title\" : $(\"#title\").val(),\r\n");
      out.write("\t\t\t\t\t\"subtitle\" : $(\"#subtitle\").val(),\r\n");
      out.write("\t\t\t\t\t\"fcontent\" : prev,\r\n");
      out.write("\t\t\t\t\t\"ccontent\" : next,\r\n");
      out.write("\t\t\t\t\t\"hash\" : $(\"#hash\").val(),\r\n");
      out.write("\t\t\t\t\t\"url\" : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}).done(function(result) {\t\t\t\t\r\n");
      out.write("\t\t\t\tif (result.result) {\r\n");
      out.write("\t\t\t\t\twindow.alert(\"포스트 작성 완료\");\r\n");
      out.write("\t\t\t\t\tlocation.href = \"/blog/\" + result.url;\r\n");
      out.write("\t\t\t\t}else{\t\t\t\t\r\n");
      out.write("\t\t\t\t\twindow.alert(\"포스트 작성 실패\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/view/blog/postWrite.jsp(304,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("obj");
      // /WEB-INF/view/blog/postWrite.jsp(304,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/blog/postWrite.jsp(304,7) '${catelist }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${catelist }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/view/blog/postWrite.jsp(305,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${obj.CATEGORY_NAME ne '전체 보기'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t<option>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${obj.CATEGORY_NAME }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\t\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
